[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  network = "pvwarden_web"

[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    
    [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"

     [entryPoints.websecure.http.tls]
      certResolver = "letsencrypt"

[certificatesResolvers.letsencrypt.acme]
  email = "email@examle.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.letsencrypt.acme.dnsChallenge]
    provider = "cloudflare"

[log]
  level = "debug"
  filePath = "/etc/traefik/access.log"